### ISSUE TITLE
v3.4.8未能成功内置okhttp:3.12.13

### ISSUE THREAD

**Issue by TxcA** [liangjingkanji/Net-okhttp3#3]
## 问题描述
Net-okhttp3:3.4.8  未能成功内置okhttp:3.12.13

## 如何复现
```
implementation("com.github.liangjingkanji:Net-okhttp3:3.4.8")
implementation("com.github.Txca:Net-okhttp3:3.4.6-R2")
```
分别使用以上依赖，`> Task :app:dependencies`

## 截图
![1](https://user-images.githubusercontent.com/15992858/170908252-95f01c2f-825e-4308-848c-443361149efc.png)
![2](https://user-images.githubusercontent.com/15992858/170908256-2e6ec76f-5a5c-48ba-8125-764b0a3fab01.png)
![3](https://user-images.githubusercontent.com/15992858/170908260-d484c4a2-e452-4edc-8dd5-bffa5979a80d.png)

## 版本
- Net: 3.4.8
- OkHttp:  -
- Gradle:  7.3.3
- Android Studio:  2021.2.1 Patch 1
- Android: -

**Comment by TxcA** [comment]
单独引入 implementation("com.squareup.okhttp3:okhttp:3.12.13")后，不手动配置分包相关规则，报错依旧，okhttp还是没能打入主包。
![x](https://user-images.githubusercontent.com/15992858/170910399-60e9ea51-32c3-4299-bf22-fb008bce52a9.png)

**Comment by liangjingkanji** [comment]
最新代码明明依赖了，有点奇怪

**Comment by TxcA** [comment]
感觉有点像 [#d26e10](https://github.com/liangjingkanji/Net-okhttp3/commit/d26e106801c10ee27d2052351fd23fa8cd66c77e#diff-b861ff3b6a2ff697ba42f23bdb4859e81170bb98de0b695d2cf4e31be98e238a) 也未能打包进`3.4.6` 这个问题。
JitPack打包有几率不是最新的代码？但是它又能读到tag了...

**Comment by liangjingkanji** [comment]
我尝试重新构建, 我测试依赖没有问题了, 建议你删除`.gradle/cache`后重新同步


> 每次重新同步gradle废了我老大功夫了, 有好办法没

**Comment by TxcA** [comment]
@liangjingkanji 情况大概确定了，**打包的问题。**

[Net 的 BaseRequest](https://github.com/liangjingkanji/Net/blob/master/net/src/main/java/com/drake/net/request/BaseRequest.kt)
[Net-okhttp3 的 BaseRequest](https://github.com/liangjingkanji/Net-okhttp3/blob/okhttp3/net/src/main/java/com/drake/net/request/BaseRequest.kt)

注意他们的import:
- Net
```kotlin
...
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull
...
```

- Net-okhttp3
```kotlin
...
import com.drake.net.compatible.toHttpUrl
import com.drake.net.compatible.toHttpUrlOrNull
...
```

---

**但是，Net-okhttp3:3.4.8.aar里import 的是`Net`的而非`Net-okhttp3`的。**
![x](https://user-images.githubusercontent.com/15992858/170915665-ffb26ec8-5af0-4931-b7c4-da43908d07b2.png)

**我还担心是我本地缓存，所以从JitPack手动下了aar解析。**
**这里明显可以看到`Companion`，但是okhttp:3.12.13还是java构建的，还未切到kotlin。所以它不可能存在`companion object`。**
[https://jitpack.io/com/github/liangjingkanji/Net-okhttp3/3.4.8/Net-okhttp3-3.4.8.aar](https://jitpack.io/com/github/liangjingkanji/Net-okhttp3/3.4.8/Net-okhttp3-3.4.8.aar)
![x](https://user-images.githubusercontent.com/15992858/170915724-a6590c70-30f9-4ae3-870d-4da07703f95f.png)

**同时，我也检查了我打的3.6.4-R2，可以发现正常使用了你写的扩展方法**
[https://jitpack.io/com/github/TxcA/Net-okhttp3/3.4.6-R2/Net-okhttp3-3.4.6-R2.aar](https://jitpack.io/com/github/TxcA/Net-okhttp3/3.4.6-R2/Net-okhttp3-3.4.6-R2.aar)

![x](https://user-images.githubusercontent.com/15992858/170916731-b996e61e-292e-464f-84ef-faad5c4bdd32.png)

---

2小时后接到这写，写到一半被抓去开会去了...

[pom](https://jitpack.io/com/github/liangjingkanji/Net-okhttp3/3.4.8/Net-okhttp3-3.4.8.pom)
现在看到 com.squareup.okhttp3 的依赖正常了。
也正常的调用了`OkHttpClientKt.toHttpUrl`。
**啥问题，咋解决的？**

---

其实我最多删删工程下的.gradle，总的大部分情况不敢动。看了下27G，头大...
最佳解决办法: 更新lib版本号，发布新版本。因为不是所有人都会清理gradle缓存（当我是借口），且同版本下存在两种不同的实现（重构建之前下载的和重构建之后下载的）（借口+1），后期debug也头大（借口+2）。

**Comment by liangjingkanji** [comment]
我删除tag然后重新创建tag后重新构建jitpack解决的

**Comment by liangjingkanji** [comment]
我只是想知道本地是否可以删除指定某个依赖而不需要删除所有依赖缓存, 方便测试而已

线上发布肯定还是需要发布新版本的, 你已经解决依赖问题了吗? 需要发布新版本不? 

> 新版本会导致不方便和Net版本号同步, 本来不打算发布的

**Comment by TxcA** [comment]
> 我删除tag然后重新创建tag后重新构建jitpack解决的

你看我发的截图没，没集成okhttp是一部分。然后BaseRequest的代码不对也奇怪。

**Comment by TxcA** [comment]
> 我只是想知道本地是否可以删除指定某个依赖而不需要删除所有依赖缓存, 方便测试而已
> 
> 线上发布肯定还是需要发布新版本的, 你已经解决依赖问题了吗? 需要发布新版本不?
> 
> > 新版本会导致不方便和Net版本号同步, 本来不打算发布的

双方同步版本，这边打副版本`-patch1` 😂

**Comment by TxcA** [comment]
我这边暂时没事，caches我已经删了，27G。肉疼，每个工程打开估计都是十多分钟了...

**Comment by liangjingkanji** [comment]
> 我这边暂时没事，caches我已经删了，27G。肉疼，每个工程打开估计都是十多分钟了...

升级新版本也行...

**Comment by TxcA** [comment]
这是否算是JitPack的bug? 快去给它提个issues😂

**Comment by liangjingkanji** [comment]
不知道如何描述, 也是第一次遇见不过问题的确很大, 最近有点忙等有空再说吧

**Comment by TxcA** [comment]
pom里没有okhttp的依赖，我都还能想得通。
但是构建后的代码和仓库里的代码不同，这是我没想明白的。

**Comment by liangjingkanji** [comment]
会不会是cherry-pick导致的标签问题

**Comment by TxcA** [comment]
[https://jitpack.io/com/github/liangjingkanji/Net-okhttp3/3.4.8/build.log](https://jitpack.io/com/github/liangjingkanji/Net-okhttp3/3.4.8/build.log)
![x](https://user-images.githubusercontent.com/15992858/170937711-d6fa87c1-43f4-490d-92c2-b692c4388fe7.png)

我检查了下你的`Net-okhttp3`，没有任何一处申明或依赖`com.github.liangjingkanji:net`，我顺便看了下我的log，同样也有这个。但是我的已经是`com.github.TxcA:Net-okhttp3`了，理应不该和`com.github.liangjingkanji:net`关联。

~~难道是包名相同引起的？如果这样，那它这个逻辑也太混乱了，不知道下次打出的包是`Net`的还是`Net-okhttp3`的。~~
对了，我还测试了下修改了包名，也有这个问题。

**Comment by liangjingkanji** [comment]
在`net`模块下的`build.gradle`有以下代码

```
apply plugin: "com.github.dcendents.android-maven"
group = "com.github.liangjingkanji"
````

我认为可能是这个被jitpack导致识别为同一个仓库

**Comment by liangjingkanji** [comment]
实际上jitpack无需任何插件导入也可以生成远程依赖, 所以我计划相关代码全部删除

**Comment by TxcA** [comment]
有可能，我删除了再打一个试试

**Comment by liangjingkanji** [comment]
当初我查询jitpack无法根据分支来创建不同依赖, 所以开新的仓库来生成新的依赖

**Comment by TxcA** [comment]
实际上代码还是在一个工程内，只是推不同的分支，所以有重复项，这样的吗?

**Comment by liangjingkanji** [comment]
jitpack并不支持这种操作, 两个都是独立的github仓库, 但是可能因为`group = "com.github.liangjingkanji"`导致被jitpack识别有误

只是我的猜测

**Comment by TxcA** [comment]
如果是这个原因，感觉jitpack的处理也不符合逻辑，虽然group一样，但是artifact不同啊。

**Comment by liangjingkanji** [comment]
可能是group+module名称生成的, 但是我看Net主仓库的依赖`3.4.8`还是正常的

**Comment by TxcA** [comment]
越来越有意思了，仓库名和未使用的`group = "com.github.liangjingkanji"`对构建都有影响。

### 1. 删除了`group = "com.github.liangjingkanji"`，但是仓库名为Net-okhttp3
可以看到log里有`Found artifact: com.github.TxcA:net:3.4.8-R2`，而不是未删除前的`Found artifact: com.github.liangjingkanji:net:3.4.8-R1`，说明`group`的确会有影响。
~~但是我并未有`Net`仓。所以推测做了类似`-SNAPSHOT`的逻辑，识别仓库名的`-`，自主去推测了主仓库。~~
并未推断，第2步已测试。
[https://jitpack.io/com/github/TxcA/Net-okhttp3/3.4.8-R2/build.log](https://jitpack.io/com/github/TxcA/Net-okhttp3/3.4.8-R2/build.log)

### 2.重命名仓库后再推了`3.8.4-R3`，
[https://jitpack.io/com/github/TxcA/Netokhttp3/3.4.8-R3/build.log](https://jitpack.io/com/github/TxcA/Netokhttp3/3.4.8-R3/build.log)
还是存在`Found artifact: com.github.TxcA:net:3.4.8-R3`。**所以仓库名字应该不影响。**

---

最后追了下，感觉你本地工程`Net-okhttp3`应该是`Net`的分支，他们在我PR前早期的提交是相同的，我提交后才出现了分岔。
[https://github.com/liangjingkanji/Net-okhttp3/commit/1828dbd60dea32a973f82e787d3a542070f83c2b](https://github.com/liangjingkanji/Net-okhttp3/commit/1828dbd60dea32a973f82e787d3a542070f83c2b)

[https://github.com/liangjingkanji/Net/commit/1828dbd60dea32a973f82e787d3a542070f83c2b](https://github.com/liangjingkanji/Net/commit/1828dbd60dea32a973f82e787d3a542070f83c2b)

---

到这了，不追了，各种特殊情况的结合出现的问题吧，但是这应该是一个bug。

**Comment by liangjingkanji** [comment]
Net-okhttp3和Net的提交并不相同只是提交信息相同, 我全部使用的是`cherry-pick`

**Comment by TxcA** [comment]
`cherry-pick` 后commit hash一样的，这东西理论不会重复。所以`cherry-pick`和直接提交，信息识别上对于第三者并不能识别出。

**Comment by liangjingkanji** [comment]
`cherry-pick`相当于两个提交, commit-hash完全不一样吧

**Comment by TxcA** [comment]
~我上面给出了连接的：~
~hash: 1828dbd60dea32a973f82e787d3a542070f83c2b 不包住还转链接了 `1828dbd60dea32a973f82e787d3a542070f83c2b`~

**Net-okhttp3**
~[https://github.com/liangjingkanji/Net-okhttp3/commit/1828dbd60dea32a973f82e787d3a542070f83c2b](https://github.com/liangjingkanji/Net-okhttp3/commit/1828dbd60dea32a973f82e787d3a542070f83c2b)~

**Net**
~[https://github.com/liangjingkanji/Net/commit/1828dbd60dea32a973f82e787d3a542070f83c2b](https://github.com/liangjingkanji/Net/commit/1828dbd60dea32a973f82e787d3a542070f83c2b)~

---

的确不同，我这边看错了。
那就不知道JitPack的推断逻辑了...

**Comment by liangjingkanji** [comment]
本仓库后续版本观察下

**Comment by TxcA** [comment]
哪天找到根本原因了来这里挖坟@我 or 我@你，我的确蛮好奇它的逻辑的~😂

**Comment by liangjingkanji** [comment]
好的
