### ISSUE TITLE
okhttp3依赖没有内置、com/drake/net/request/BaseRequest.kt中的import有误

### ISSUE THREAD

**Issue by XuchengJie** [liangjingkanji/Net-okhttp3#5]
## 问题描述
android4.4报错
错误1：okhttp3没有内置依赖，需手动依赖
             androidx.startup.StartupException: java.lang.NoClassDefFoundError: okhttp3.OkHttpClient$Builder
错误2：java.lang.NoSuchFieldError: okhttp3.HttpUrl.Companion

报错原因是tag中的代码和okhttp3分支不一致而且是错误的
https://github.com/liangjingkanji/Net-okhttp3/blob/3.6.0/net/src/main/java/com/drake/net/request/BaseRequest.kt
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull

https://github.com/liangjingkanji/Net-okhttp3/blob/okhttp3/net/src/main/java/com/drake/net/request/BaseRequest.kt中import：
import com.drake.net.compatible.toHttpUrl
import com.drake.net.compatible.toHttpUrlOrNull

上面代码和okhttp3不一致的情况从tag 3.4.13开始就存在，目前能正常使用的版本就是3.4.12.

## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

导致报错

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net: Net-okhttp3:3.6.0
- OkHttp:  3.12.13
- Android:  4.4
- Gradle:  
- Android Studio:

**Comment by liangjingkanji** [comment]
你更新太快了, 等我更新下

**Comment by liangjingkanji** [comment]
你重新拉取`3.6.0`版本试下, 我不清楚为什么之前的版本存在代码缺失

可能需要你清除gradle下载依赖缓存

**Comment by XuchengJie** [comment]
好，我试试

**Comment by XuchengJie** [comment]
可以了，大佬，终于有了一个正常可用的版本

**Comment by liangjingkanji** [comment]
不是一直可以正常使用吗? 我试下依赖低版本

我也没用过这个库, 这是有Net另外作者的需求才创建的库

**Comment by XuchengJie** [comment]
从3.4.13开始都有这个问题，你可以看看tag里面同样的文件

**Comment by Jerry930326** [comment]
okhttp的依赖还是没有内置

**Comment by liangjingkanji** [comment]
> okhttp的依赖还是没有内置

我在sample里面远程依赖试了下没问题, 可能你需要删除gradle缓存依赖重新拉取

**Comment by Jerry930326** [comment]
可能是我只删了net的gradle缓存，没删okhttp的gradle缓存

**Comment by XuchengJie** [comment]
> okhttp的依赖还是没有内置

看pom文件是依赖了，你删缓存

**Comment by liangjingkanji** [comment]
> 可能是我只删了net的gradle缓存，没删okhttp的gradle缓存

你不是要使用Android 4.3 (API level 18)来开发吗? 那我建议你拉取仓库手动调整`minSdkVersion`编译成aar来依赖使用

`API level 18` 版本太古老我修改远程依赖会需要修改一系列依赖库不太合适

**Comment by Jerry930326** [comment]
> > 可能是我只删了net的gradle缓存，没删okhttp的gradle缓存
> 
> 你不是要使用Android 4.3 (API level 18)来开发吗? 那我建议你拉取仓库手动调整`minSdkVersion`编译成aar来依赖使用
> 
> `API level 18` 版本太古老我修改远程依赖会需要修改一系列依赖库不太合适

好的
